apiVersion: apps/v1
kind: Deployment
metadata:
  name: telefono-movil-service
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"             # Path to metrics endpoint
        prometheus.io/probe: "true"                # Enable Prometheus probe
        prometheus.io/port: "8080"                 # Port where metrics are exposed
        prometheus.io/scrape: "true"               # Enable scraping by Prometheus
    spec:
      containers:
        - name: telefono-movil-container
          image: your-image:latest                  # Replace with your actual container image
          ports:
            - containerPort: 8080                     # Port your service listens on
